### ISSUE TITLE
Original Mirrors duplicated 

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#1072] opened 2016-07-13 00:51 UTC
On the trucks who used original mirrors system, the left mirror is duplicated on the right.

Look at the pictures above.
![screenshot_2016-07-12_20-49-25_1](https://cloud.githubusercontent.com/assets/16364065/16788369/6964a7b0-4872-11e6-96e0-0ce57232de14.png)
![screenshot_2016-07-12_20-49-30_1](https://cloud.githubusercontent.com/assets/16364065/16788370/6b161620-4872-11e6-8ea0-379fc99f22a1.png)

**Comment by Hotrod55** [comment] 2016-07-13 01:08
This is caused by OGRE 1,x's (poor) material management system, It's always been like this. It can only render one of the same material at the same time. (Videocameras also suffer from this issue.) The other mirror won't be duplicated if you zoom in using FOV.

**Comment by WillyB1337** [comment] 2016-07-13 01:15
Well, I hope this issue will be resolved in the next OGRE 2.X 

After trying to look directly on the others mirrors ( 90 degrees to the right), It shows correctly.

Thanks for the fix anyway :+1:

**Comment by only-a-ptr** [comment] 2017-01-31 14:30
I looked in the code in the meantime.

Old-mirrors are really designed to render only one mirror at a time, and disable the others. The code attempts to find a mirror which is visible on screen and closest to camera, render that and disable all others (make them show the gray-ish surface). But it may be broken.

**Comment by Michael10055** [comment] 2017-06-09 23:32
Fixed in #1271

**Closed by Michael10055** 2017-06-09 23:32 UTC
Labels: bug
