### ISSUE TITLE
Can not load vehicles with special characters in authors section 

### ISSUE THREAD

**Issue by Hotrod55** [RigsOfRods/rigs-of-rods#364] opened 2015-08-07 13:10 UTC
NothingToDo posted this in the RoR Skype group, I thought I'd post a bug report on it since I found the cause of it.
 
Using this vehicle: http://www.rigsofrods.com/repository/view/5548
The authors section has a special character in it, causing a runtime error to occur.
author Lampe fl**è**ches -1 dolmen62
![2015-08-07_08-50-42](https://cloud.githubusercontent.com/assets/11002490/9136154/53683db0-3ce2-11e5-9234-ae57c3effd76.png)
RoR.log says the parser ignores the line:
```
08:50:22:  ===== LOADING VEHICLE: afc4UID-a4e3UIDsprinterasf.truck
08:50:22:  == Parsing vehicle file: afc4UID-a4e3UIDsprinterasf.truck
08:50:22:  == Parsing done, report:

#FF3300 ERROR #FFFFFF (Section globals)
	Line (11): author Lampe flèches -1 dolmen62
	Message: Invalid line, ignoring...
#FFFF00 WARNING #FFFFFF (Section meshwheels)
	Line (673): -36
	Message: Encountered node with illegal negative number: '-36', parsing as positive '36' for backwards compatibility. Please fix as soon as possible.



08:50:22:  == Validating vehicle: Sprinter ASF
08:50:22:  == Validating done OK
```
Does not happen in 0.4.0.7.

**Comment by only-a-ptr** [comment] 2015-11-13 13:44
@Hotrod55 Thanks for reporting.

**Comment by only-a-ptr** [comment] 2015-11-18 00:38
@Hotrod55 The problem is RoR assumes truckfiles saved in UTF-8 encoding. This truck is in https://en.wikipedia.org/wiki/Windows-1252. I discovered it by saving file to disk, opening it in firefox and then switching [Display->character set->*] options until it matched. There is no way to auto-detect it.

I'll figure something out tho.

**Comment by only-a-ptr** [comment] 2015-11-19 21:12
Reproduced. Fixing in progress....

**Comment by only-a-ptr** [comment] 2016-02-02 15:18
Fixed in upstream.

**Closed by only-a-ptr** 2016-02-02 15:18 UTC
Labels: bug
