### ISSUE TITLE
Wheels2 crash the game in multiplayer 

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1149] opened 2016-10-13 15:28 UTC
Vehicles with wheels2 crash the game in multiplayer.

**Vehicles tested with:**
- [SDSArgo_1.zip](https://github.com/RigsOfRods/rigs-of-rods/files/527500/SDSArgo_1.zip)
- [Trailmasher.zip](https://github.com/RigsOfRods/rigs-of-rods/files/527502/Trailmasher.zip)

Function  | File(Line)   
---|---  
**RoR!RigSpawner::BuildWheelObjectAndNodes**| **f:/rigs-of-rods/source/main/physics/rigspawner.cpp(4760)**  
RoR!RigSpawner::AddWheel| f:/rigs-of-rods/source/main/physics/rigspawner.cpp(5010)  
RoR!RigSpawner::ProcessWheel2| f:/rigs-of-rods/source/main/physics/rigspawner.cpp(5591)  
RoR!RigSpawner::SpawnRig| f:/rigs-of-rods/source/main/physics/rigspawner_processcontrol.cpp(16707566)  
RoR!Beam::LoadTruck| f:/rigs-of-rods/source/main/physics/beam.cpp(5756)  
RoR!Beam::Beam| f:/rigs-of-rods/source/main/physics/beam.cpp(5468)  
RoR!BeamFactory::CreateLocalRigInstance| f:/rigs-of-rods/source/main/physics/beamfactory.cpp(215)  
RoR!RoRFrameListener::updateEvents| f:/rigs-of-rods/source/main/gameplay/rorframelistener.cpp(1308)  
RoR!RoRFrameListener::frameStarted| f:/rigs-of-rods/source/main/gameplay/rorframelistener.cpp(1571)  
WARNING: Stack unwind information not available. Following frames may be wrong.| -  
OgreMain| -  
OgreMain| -  
RoR!RoR::MainThread::EnterGameplayLoop| f:/rigs-of-rods/source/main/mainthread.cpp(862)  
RoR!RoR::MainThread::Go| f:/rigs-of-rods/source/main/mainthread.cpp(439)  
RoR!main| f:/rigs-of-rods/source/main/main.cpp(250)  
RoR!WinMain| f:/rigs-of-rods/source/main/main.cpp(256)  
RoR!__scrt_common_main_seh| f:/dd/vctools/crt/vcstartup/src/startup/exe_common.inl(253)  
kernel32!BaseThreadInitThunk| -  
ntdll!__RtlUserThreadStart| -  
ntdll!_RtlUserThreadStart| -

**Comment by ulteq** [comment] 2016-10-13 18:15
I can't reproduce it on linux.

**Comment by disloyalpick** [comment] 2016-10-13 20:10
On windows cannot reproduce with the 6X6 Daf Paris-Dakar.  Also possibly a parser error.

![screenshot_2016-10-13_16-09-21_1](https://cloud.githubusercontent.com/assets/13305403/19365179/8a9866d4-915f-11e6-9689-0506c74dec4f.png)

**Comment by AnotherFoxGuy** [comment] 2016-10-14 07:37
The crash seems only to happen in multiplayer.

**Comment by AnimosusTheWolf** [comment] 2016-10-14 07:37
Reproduced game crash when spawning a vehicle with wheels2 in a multiplayer session.

[RoR.log](http://pastebin.com/tdFQRuqx)

**Comment by ulteq** [comment] 2016-10-14 08:46
The crash happens in this line: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/RigSpawner.cpp#L6656
```
node.friction_coef = node_defaults->friction;
```

**Comment by ulteq** [comment] 2016-10-14 17:57
> Also possibly a parser error.

@disloyalpick that bug is fixed in current upstream.

**Closed** 2016-10-15 10:40 UTC
Labels: bug, crash, multiplayer
