### ISSUE TITLE
water reflection glitches

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1455] opened 2018-02-01 19:57 UTC
load a terrain with water, exit to menu change the sky and load again the terrain.

**Comment by only-a-ptr** [comment] 2018-02-01 22:01
@Speciesx What water type? What terrains did you test with? Post RoR.log

**Comment by Speciesx** [comment] 2018-02-01 22:47
Water type Reflection + refraction, happens on every terrain with water.
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/1687490/RoR.log)

**Comment by only-a-ptr** [comment] 2018-02-04 14:26
Heh, curious... looks like the water gets stuck with the last reflection from the previous session.

Here I drove in water with Manitou, then switched sky from Sandstorm to Caelum and drove to water again with AgoraS: but the reflection was stuck on Manitou 🤣 

![obrazek](https://user-images.githubusercontent.com/491088/35778532-b2fb66e2-09bf-11e8-8649-c80bb0fd4904.png)

**Comment by only-a-ptr** [comment] 2018-02-04 14:35
Closing as duplicate of https://github.com/RigsOfRods/rigs-of-rods/issues/50 becuase I just checked that this happen regardless on the Sky setting - I just tested with Auriga map and Caelum still enabled - the water was stuck with last snapshot from previous session.

**Closed by only-a-ptr** 2018-02-04 14:35 UTC
Labels: bug, graphics
