### ISSUE TITLE
water surface is upside down

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#986] opened 2016-05-24 23:00 UTC
Water type: reflection + refraction (speed and quality)
Reflection and 'water splashes'? are underwater.
https://youtu.be/opRj8fmQTtc

And here how it looks like with water type reflection.
https://youtu.be/ej2qi6rTh2M

**Comment by ulteq** [comment] 2016-05-26 10:10
Was it different in earlier versions?

**Comment by Speciesx** [comment] 2016-05-26 10:16
no

**Comment by adriansnetlis** [comment] 2016-07-19 10:47
In those videos it doesn't seem even 1 billionth bad as in mine. It even doesn't seem upside down. For me it is, though.

**Comment by only-a-ptr** [comment] 2018-02-11 20:32
I just tested and I couldn't reproduce the upside-down reflection which @adriansnetlis showed in the video. I'd have to see RoR.log from him, from the FPS of the video it seems he's using some weak troublemaker video chip.

**Comment by ulteq** [comment] 2019-01-17 14:24
Should be fixed with: https://github.com/RigsOfRods/rigs-of-rods/pull/2045

**Closed by ulteq** 2019-01-17 14:24 UTC
Labels: graphics
