### ISSUE TITLE
game "crash" while pressing shift & numpad +

### ISSUE THREAD

**Issue by 4x4convoy** [RigsOfRods/rigs-of-rods#1249] opened 2016-11-17 22:56 UTC
I figured out that in version 0.4.7.0 while changing the time, if you hold just numpad + to change the time, it works fine. But if you if you press numpad + & shift at the same time, the game does some weird things. The game freezes and you cant do anything. If you Alt Tab out of the game, it stops responding, but after awhile, the game goes back to normal and you can drive around again.

**Comment by Michael10055** [comment] 2016-11-17 23:06
This issue has been happening ever since the OGRE 1.9 port. It's already known but I can't find an existing issue on it.

**Comment by AnotherFoxGuy** [comment] 2016-11-18 07:55
Duplicate of #1080

**Closed by AnotherFoxGuy** 2016-11-18 07:55 UTC
Labels: duplicate
