### ISSUE TITLE
Game crashes on Linux with segfault

### ISSUE THREAD

**Issue by IKRadulov** [RigsOfRods/rigs-of-rods#1312] opened 2017-04-07 15:03 UTC
Distro : Manjaro
Version of game : Build from source .

Attached the output of the game :
[segfault.error.zip](https://github.com/RigsOfRods/rigs-of-rods/files/905979/segfault.error.zip)

**Comment by fidoj** [comment] 2017-06-06 23:46
i can second this, distro ubuntu, happens when entering a vehicle with A camera, i can spawn loads and enter them fine they function as expected.

**Comment by fidoj** [comment] 2017-06-07 00:00
its caused by the engine not the camera

**Comment by fidoj** [comment] 2017-06-07 00:18
i modded the default bus and removed the engine for test.truck
i load both this is exert from terminal
` ===== LOADING VEHICLE: test.truck
 == Parsing vehicle file: test.truck
 == Parsing done, report:

#FFFF00 WARNING #FFFFFF (Section wheels)
	Line (943): -102
	Message: Encountered node with illegal negative number: '-102', parsing as positive '102' for backwards compatibility. Please fix as soon as possible.
#FFFF00 WARNING #FFFFFF (Section wheels)
	Line (945): -98
	Message: Encountered node with illegal negative number: '-98', parsing as positive '98' for backwards compatibility. Please fix as soon as possible.



 == Validating vehicle: Bus TEST
 == Validating done OK
 == Spawning vehicle: Bus TEST
ResourceTrueTypeFont: Font 'DefaultDashFont' using texture size 128 x 128.
ResourceTrueTypeFont: Font 'DefaultDashFont' using real height 18 pixels.
ResourceTrueTypeFont: Font 'Digital-7' using texture size 512 x 256.
ResourceTrueTypeFont: Font 'Digital-7' using real height 65 pixels.
ResourceTrueTypeFont: Font 'Digital-7-18' using texture size 128 x 256.
ResourceTrueTypeFont: Font 'Digital-7-18' using real height 24 pixels.
Mesh: Loading beam.mesh.
Texture: RustySteel.dds: Loading 1 faces(PF_DXT1,256x256x1) with 8 custom mipmaps from Image. Internal format is PF_DXT1,256x256x1.
Texture: wheelface.dds: Loading 1 faces(PF_DXT1,64x64x1) with 6 custom mipmaps from Image. Internal format is PF_DXT1,64x64x1.
Texture: wheelband1.dds: Loading 1 faces(PF_DXT1,32x32x1) with 5 custom mipmaps from Image. Internal format is PF_DXT1,32x32x1.
Texture: wheelfaceb.dds: Loading 1 faces(PF_DXT1,64x64x1) with 6 custom mipmaps from Image. Internal format is PF_DXT1,64x64x1.
Texture: wheelband2.dds: Loading 1 faces(PF_DXT1,32x64x1) with 6 custom mipmaps from Image. Internal format is PF_DXT1,32x64x1.
Texture: flare.dds: Loading 1 faces(PF_DXT5,128x128x1) with 7 custom mipmaps from Image. Internal format is PF_DXT5,128x128x1.
Texture: blinkflare.dds: Loading 1 faces(PF_DXT5,128x128x1) with 7 custom mipmaps from Image. Internal format is PF_DXT5,128x128x1.
Texture: brakeflare.dds: Loading 1 faces(PF_DXT5,128x128x1) with 7 custom mipmaps from Image. Internal format is PF_DXT5,128x128x1.
Mesh: Loading dirwheel.mesh.
Texture: dirwheel.dds: Loading 1 faces(PF_DXT1,256x256x1) with 8 custom mipmaps from Image. Internal format is PF_DXT1,256x256x1.
Mesh: Loading dashboard.mesh.
Mesh: Loading leftmirror.mesh.
Texture: mirror.dds: Loading 1 faces(PF_DXT1,32x32x1) with 5 custom mipmaps from Image. Internal format is PF_DXT1,32x32x1.
Texture: mirrorlayer.dds: Loading 1 faces(PF_DXT5,128x256x1) with 8 custom mipmaps from Image. Internal format is PF_DXT5,128x256x1.
Mesh: Loading rightmirror.mesh.
Mesh: Loading seat.mesh.
Texture: seat.dds: Loading 1 faces(PF_DXT1,256x256x1) with 8 custom mipmaps from Image. Internal format is PF_DXT1,256x256x1.
Texture: 95bbUID-bus2.dds: Loading 1 faces(PF_DXT3,1024x512x1) with 10 custom mipmaps from Image. Internal format is PF_DXT3,1024x512x1.
Texture: 95bbUID-bus2_emissive.dds: Loading 1 faces(PF_DXT1,512x256x1) with 9 custom mipmaps from Image. Internal format is PF_DXT1,512x256x1.
 == RigSpawner: WARNING (Keyword ~Unknown~) vehicle uses no GUID, skinning will be impossible
TOTAL VEHICLE MASS: 20835 kg
Loading WAV file default_break.wav
SoundScriptInstance: instance created: defaults.soundscript-0-0
BEAM: memory stats following
BEAM: beam memory: 212480 B (1328 x 160 B) / 800000
BEAM: node memory: 29700 B (297 x 100 B) / 100000
BEAM: shock memory: 684 B (9 x 76 B) / 380000
BEAM: prop memory: 2656 B (4 x 664 B) / 132800
BEAM: wheel memory: 3264 B (6 x 544 B) / 34816
BEAM: rigidifier memory: 0 B (0 x 56 B) / 5600
BEAM: flare memory: 1120 B (14 x 80 B)
BEAM: truck memory used: 249904 B (244 kB)
BEAM: truck memory allocated: 1820480 B (1777 kB)
 ===== DONE LOADING VEHICLE
Rig loading profiler report:
	Beam::Beam()                 | prepare loading: 0.000490 sec
	Beam::LoadTruck()            | open file:       0.000140 sec
	Beam::LoadTruck()            | create parser:   0.000015 sec
	Beam::LoadTruck()            | prepare parser:  0.000026 sec
	Beam::LoadTruck()            | run parser:      0.003869 sec
	Beam::LoadTruck()            | finalize parser: 0.010685 sec
	Beam::LoadTruck()            | post-parse:      0.000059 sec
	Beam::LoadTruck()            | setup validator: 0.000009 sec
	Beam::LoadTruck()            | run validator:   0.000007 sec
	Beam::LoadTruck()            | post-validation: 0.000011 sec
	Beam::LoadTruck()            | setup spawner:   0.000023 sec
	Beam::LoadTruck()            | add modules:     0.000001 sec
	Beam::LoadTruck()            | run spawner:     0.036105 sec
	Beam::LoadTruck()            | log spawner:     0.000098 sec
	Beam::LoadTruck()            | process fixes:   0.000040 sec
	Beam::LoadTruck()            | calc masses:     0.000049 sec
	Beam::LoadTruck()            | soundsources:    0.000171 sec
	Beam::LoadTruck()            | calc node graph: 0.000212 sec
	Beam::LoadTruck()            | bounding boxes:  0.000003 sec
	Beam::LoadTruck()            | groundmodel:     0.000135 sec
	Beam::LoadTruck()            | load dashboards: 0.000001 sec
	BeamFactory::createLocal()   | post-process:    0.000692 sec
	RigLoadingProfiler::Report() | compose report:  0.000013 sec
Widget property 'Text_TextAlign' have type prefix - use 'TextAlign' instead [MapEntity.layout]
Widget property 'Text_FontHeight' have type prefix - use 'FontHeight' instead [MapEntity.layout]
static map icon not found: icon_load.dds
Texture: icon_load_sleeping.dds: Loading 1 faces(PF_DXT5,64x64x1) with 6 custom mipmaps from Image. Internal format is PF_DXT5,64x64x1.
[RoR|Globals] Updating "sim_state_active": [SELECTING] => [RUNNING]
[RoR|Globals] Updating "sim_state_active": [RUNNING] => [SELECTING]
Texture: agora_95bbUID-agoral.truck.mini.dds: Loading 1 faces(PF_DXT5,256x256x1) with 8 custom mipmaps from Image. Internal format is PF_DXT5,256x256x1.
 ===== LOADING VEHICLE: 95bbUID-agoral.truck
 == Parsing vehicle file: 95bbUID-agoral.truck
 == Parsing done, report:

#FFFF00 WARNING #FFFFFF (Section wheels)
	Line (943): -102
	Message: Encountered node with illegal negative number: '-102', parsing as positive '102' for backwards compatibility. Please fix as soon as possible.
#FFFF00 WARNING #FFFFFF (Section wheels)
	Line (945): -98
	Message: Encountered node with illegal negative number: '-98', parsing as positive '98' for backwards compatibility. Please fix as soon as possible.



 == Validating vehicle: Bus RVI Agora L
 == Validating done OK
 == Spawning vehicle: Bus RVI Agora L
duplicate resource name 'DefaultDashFont'
ResourceTrueTypeFont: Font 'DefaultDashFont' using texture size 128 x 128.
ResourceTrueTypeFont: Font 'DefaultDashFont' using real height 18 pixels.
duplicate resource name 'Digital-7'
ResourceTrueTypeFont: Font 'Digital-7' using texture size 512 x 256.
ResourceTrueTypeFont: Font 'Digital-7' using real height 65 pixels.
duplicate resource name 'Digital-7-18'
ResourceTrueTypeFont: Font 'Digital-7-18' using texture size 128 x 256.
ResourceTrueTypeFont: Font 'Digital-7-18' using real height 24 pixels.
 == RigSpawner: WARNING (Keyword ~Unknown~) vehicle uses no GUID, skinning will be impossible
TOTAL VEHICLE MASS: 20835 kg
Loading WAV file default_diesel_idle.wav
Loading WAV file default_diesel_low.wav
Loading WAV file default_diesel_medium.wav
Loading WAV file default_diesel_high.wav
SoundScriptInstance: instance created: defaults.soundscript-1-1
Loading WAV file default_diesel_force.wav
SoundScriptInstance: instance created: defaults.soundscript-1-2
Loading WAV file default_brakes.wav
SoundScriptInstance: instance created: defaults.soundscript-1-3
Loading WAV file default_parking_brakes.wav
SoundScriptInstance: instance created: defaults.soundscript-1-4
Loading WAV file default_reverse_beep.wav
SoundScriptInstance: instance created: defaults.soundscript-1-5
Loading WAV file default_turbo.wav
SoundScriptInstance: instance created: defaults.soundscript-1-6
Loading WAV file default_turbo_bov.wav
SoundScriptInstance: instance created: defaults.soundscript-1-7
Loading WAV file default_wastegate_flutter.wav
SoundScriptInstance: instance created: defaults.soundscript-1-8
Loading WAV file default_valve.wav
SoundScriptInstance: instance created: defaults.soundscript-1-9
Loading WAV file default_starter_start.wav
Loading WAV file default_starter_stop.wav
Loading WAV file default_starter.wav
SoundScriptInstance: instance created: defaults.soundscript-1-10
Loading WAV file default_turn_signal.wav
SoundScriptInstance: instance created: defaults.soundscript-1-11
Loading WAV file default_horn_start.wav
Loading WAV file default_horn_stop.wav
Loading WAV file default_horn.wav
SoundScriptInstance: instance created: defaults.soundscript-1-12
Loading WAV file default_shift.wav
SoundScriptInstance: instance created: defaults.soundscript-1-13
Loading WAV file default_screetch.wav
SoundScriptInstance: instance created: defaults.soundscript-1-14
SoundScriptInstance: instance created: defaults.soundscript-1-15
BEAM: memory stats following
BEAM: beam memory: 212480 B (1328 x 160 B) / 800000
BEAM: node memory: 29700 B (297 x 100 B) / 100000
BEAM: shock memory: 684 B (9 x 76 B) / 380000
BEAM: prop memory: 2656 B (4 x 664 B) / 132800
BEAM: wheel memory: 3264 B (6 x 544 B) / 34816
BEAM: rigidifier memory: 0 B (0 x 56 B) / 5600
BEAM: flare memory: 1120 B (14 x 80 B)
BEAM: truck memory used: 249904 B (244 kB)
BEAM: truck memory allocated: 1820480 B (1777 kB)
Texture: autogears.png: Loading 1 faces(PF_A8R8G8B8,26x101x1) Internal format is PF_A8R8G8B8,26x101x1.
Texture: speedo160_analog.png: Loading 1 faces(PF_A8R8G8B8,300x300x1) Internal format is PF_A8R8G8B8,300x300x1.
Texture: rpm_gauge_4000.png: Loading 1 faces(PF_A8R8G8B8,300x300x1) Internal format is PF_A8R8G8B8,300x300x1.
Texture: antilockbrake_v2-0.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: tractioncontrol-0.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: turbo_v3.png: Loading 1 faces(PF_A8R8G8B8,200x200x1) Internal format is PF_A8R8G8B8,200x200x1.
Texture: redneedle_v2.png: Loading 1 faces(PF_A8R8G8B8,600x600x1) Internal format is PF_A8R8G8B8,600x600x1.
Texture: needle_prt2.png: Loading 1 faces(PF_A8R8G8B8,72x72x1) Internal format is PF_A8R8G8B8,72x72x1.
Texture: littlelights.png: Loading 1 faces(PF_A8R8G8B8,512x128x1) Internal format is PF_A8R8G8B8,512x128x1.
Texture: ign-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: batt-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: lopress-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: clutch-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: secured-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: locked-0.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: lights-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: pbrake-off.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) Internal format is PF_A8R8G8B8,64x64x1.
Texture: anglo_v.png: Loading 1 faces(PF_A8R8G8B8,200x180x1) Internal format is PF_A8R8G8B8,200x180x1.
Texture: anglo_h.png: Loading 1 faces(PF_A8R8G8B8,200x180x1) Internal format is PF_A8R8G8B8,200x180x1.
 ===== DONE LOADING VEHICLE
Rig loading profiler report:
	Beam::Beam()                 | prepare loading: 0.001269 sec
	Beam::LoadTruck()            | open file:       0.000228 sec
	Beam::LoadTruck()            | create parser:   0.000018 sec
	Beam::LoadTruck()            | prepare parser:  0.000040 sec
	Beam::LoadTruck()            | run parser:      0.003909 sec
	Beam::LoadTruck()            | finalize parser: 0.010420 sec
	Beam::LoadTruck()            | post-parse:      0.000030 sec
	Beam::LoadTruck()            | setup validator: 0.000012 sec
	Beam::LoadTruck()            | run validator:   0.000003 sec
	Beam::LoadTruck()            | post-validation: 0.000010 sec
	Beam::LoadTruck()            | setup spawner:   0.000012 sec
	Beam::LoadTruck()            | add modules:     0.000001 sec
	Beam::LoadTruck()            | run spawner:     0.033072 sec
	Beam::LoadTruck()            | log spawner:     0.000123 sec
	Beam::LoadTruck()            | process fixes:   0.000035 sec
	Beam::LoadTruck()            | calc masses:     0.000038 sec
	Beam::LoadTruck()            | soundsources:    0.003403 sec
	Beam::LoadTruck()            | calc node graph: 0.000298 sec
	Beam::LoadTruck()            | bounding boxes:  0.000003 sec
	Beam::LoadTruck()            | groundmodel:     0.000137 sec
	Beam::LoadTruck()            | load dashboards: 0.026040 sec
	BeamFactory::createLocal()   | post-process:    0.000769 sec
	RigLoadingProfiler::Report() | compose report:  0.000013 sec
Widget property 'Text_TextAlign' have type prefix - use 'TextAlign' instead [MapEntity.layout]
Widget property 'Text_FontHeight' have type prefix - use 'FontHeight' instead [MapEntity.layout]
static map icon not found: icon_truck.dds
Texture: icon_truck_sleeping.dds: Loading 1 faces(PF_DXT5,64x64x1) with 6 custom mipmaps from Image. Internal format is PF_DXT5,64x64x1.
[RoR|Globals] Updating "sim_state_active": [SELECTING] => [RUNNING]
Segmentation fault (core dumped)
`

**Comment by only-a-ptr** [comment] 2017-09-06 09:31
Is this still actual? Can somebody re-test please?

Also, tell me which map and vehicle are you using to reproduce it please.

**Comment by only-a-ptr** [comment] 2017-12-01 10:51
Closing - not enough info to investigate.

**Closed by only-a-ptr** 2017-12-01 10:51 UTC
Labels: crash, Linux
