### ISSUE TITLE
Automatically change N/B to current terrain elevation

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#168] opened 2015-05-02 22:22 UTC
I know this probably isn't a bug, but on non-flat terrains when you try spawning a car in the hills, it spawns underground then flies up super high. Maybe in the next version automatically change the N/B to the current elevation when spawning vehicles.

**Comment by Hiradur** [comment] 2015-10-24 18:05
Closing as duplicate of #153. Feel free to reopen if you disagree.

**Closed by Hiradur** 2015-10-24 18:05 UTC
Labels: enhancement
