### ISSUE TITLE
HDR on Linux

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#117] opened 2015-03-06 21:21 UTC
Had this problem also with .38, on various cards (nvidia 9600, intel hd 4600).

Enabling HDR causes this: http://postimg.org/image/qnbt56mld/
An older post here: http://www.rigsofrods.com/threads/91849-HDR-not-working

It would be nice to have HDR on linux! :)

**Comment by Max98** [comment] 2015-03-06 21:29
Seriously, I laughed so hard on this one!
I don't have any experience with shaders so I won't take a look at it for the moment. Someone else with the needed experience should take a look through.

**Comment by tritonas00** [comment] 2015-03-06 21:40
yeah seems like a broken old tv or something.. :P

The funny thing is that it works in windows even inside virtualbox!

**Comment by Hiradur** [comment] 2015-08-01 07:04
I replaced the HDR code in RoR with the code from the Ogre 1.8 demos (before it was also taken from Ogre but probably from 1.7). However, the problem persists so maybe the problem is coming from somewhere else.

**Comment by Hiradur** [comment] 2015-08-05 11:30
fixed in my repo

**Comment by tritonas00** [comment] 2015-08-05 23:36
Nice!!!

**Closed** 2015-08-09 17:19 UTC
Labels: bug, graphics, Linux
