### ISSUE TITLE
Cars break a little after idling

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#423] opened 2015-08-23 00:17 UTC
The parts of a lot of cars that are flexbodied and have removable parts seem to "break" or act like a ragdoll even when the car has not been moving at all. Sometimes you can't see what broke but you could hear the breaking sound Example:

Before:
![screenshot_1](https://cloud.githubusercontent.com/assets/7621364/9426374/805b27fe-48f1-11e5-8bb2-0340afb6cf83.jpg)

After (~5 seconds later, hasn't moved yet. notice the mirrors):
![screenshot_2](https://cloud.githubusercontent.com/assets/7621364/9426377/91e27e64-48f1-11e5-874d-d287a08f074a.jpg)

**Comment by gigapouch** [comment] 2015-08-26 03:03
This happened in 0.38, but not to this extent. Here's another example:
Before:
![screenshot_4](https://cloud.githubusercontent.com/assets/7621364/9484675/406e1046-4b64-11e5-8f79-53831be94711.jpg)
After (2 seconds later:)
![screenshot_5](https://cloud.githubusercontent.com/assets/7621364/9484683/5396a052-4b64-11e5-9592-9166f7dc3521.jpg)

**Comment by Max98** [comment] 2015-08-26 13:59
Are you using OpenGL?

**Comment by gigapouch** [comment] 2015-08-26 21:48
Yes, it's the only option. How would it make any difference if OpenGL and DirectX are for displaying stuff?

**Comment by DarthCainRor** [comment] 2015-08-27 04:18
Because it's a known bug to happen in OpenGL, has been that way since Gabe released his stuff I believe. https://github.com/RigsOfRods/rigs-of-rods/issues/28

**Comment by Max98** [comment] 2015-08-27 07:21
Duplicate of #28

**Closed by Max98** 2015-08-27 07:21 UTC
Labels: needs confirmation

**Comment by TechGiga** [comment] 2015-08-29 20:47
Gabester's cars always spawn with a few deformed beams anyway.
