### ISSUE TITLE
Possible render bug and crash after ctrl+alt+canc

### ISSUE THREAD

**Issue by KinG-InFeT** [RigsOfRods/rigs-of-rods#2166] opened 2019-01-31 20:47 UTC
Hi,

after ctrl+alt+canc and exit with Esc button, out this error and crash
![image](https://user-images.githubusercontent.com/193969/52084107-974ed880-25a1-11e9-9874-2e5f14f69039.png)

moreover, the ground seems to flicker between green and black patches.
The terrain load is: http://forum.rigsofrods.org/resources/top-gear-test-track.212/

**Comment by CuriousMike56** [comment] 2019-01-31 20:48
#2024

**Comment by AnotherFoxGuy** [comment] 2019-02-01 12:02
Duplicate of #2024

**Closed by AnotherFoxGuy** 2019-02-01 12:02 UTC
Labels: duplicate
