### ISSUE TITLE
Make cinecam not important to enter vehicle

### ISSUE THREAD

**Issue by Max98** [RigsOfRods/rigs-of-rods#329] opened 2015-07-24 05:41 UTC
This has me confusing, if you don't have a cinecam, you can't traditionally enter a vehicle, but yo ucan enter it via the simulation menu, and there are not glitch/bugs.
It would also be helpful for modders.
Also, some mods out there do not want to have an interior camera.

**Comment by only-a-ptr** [comment] 2015-07-27 07:27
Curious.

Knowing RoR, there is probably some obscure motivation behind this, and even if it were originally a bug, it would have become a feature until now.

I assume this mechanism exists to differentiate between vehicles which player obviously wants to enter (cars, trucks, boats) and vehicles which the may not even expect to enter (warehouse cranes, mechanical doors, trailers, loads, other by-standing machinery). The player could get confused if he walks to a truck inside a warehouse, presses Enter but instead of entering that truck he ends up in some overhead crane which he didn't even know was there.

Anyway, I agree that we should add an explicit option to control this.

**Comment by Max98** [comment] 2015-07-27 08:14
Then what is the camera for? :P 
I don't think these machines you talked about, have a camera.

**Comment by fidoj** [comment] 2015-08-12 14:44
not being able to enter a load is by design to stop you from accidental entering a trailer instead of the truck towing it, the problem is the way you enter a vehicle and the way we are forced to design vehicles, most of my trailers have larger physics models then they perspectively do, if those trailers could be entered it would be like putting 2 cars next to each other and expecting to get in 1, but get in the other. If i was to design a load you could sit in i would include a camera, BUT then the error remains for gui, as the trailer would not need 1. so an option to have a passenger seat would suffice. maybe options for what the controls there are.

**Comment by Hiradur** [comment] 2015-10-24 08:39
Closing since it's a "feature"

**Comment by only-a-ptr** [comment] 2015-11-03 16:55
I'm re-scheduling this as a low priority enhancement. An implicit decision based on presence of cinecam is not an optimal solution.

Ideally, the game would highlight (bright outline) the wehicle which would get entered, eventually highlighting multiple vehicles and letting the player cycle through them with a TAB key or something.

The truckfile should also contain explicit control over this.

**Comment by Michael10055** [comment] 2017-07-19 14:35
Closing this as it is possible to enter something that doesn't have a cinecam.

**Closed by Michael10055** 2017-07-19 14:35 UTC
Labels: enhancement, low-priority
