### ISSUE TITLE
Mods.cache can't be written in.

### ISSUE THREAD

**Issue by MicroSpam** [RigsOfRods/rigs-of-rods#284] opened 2015-06-29 03:14 UTC
Every time I try to start the program, I always get this error message: http://prntscr.com/7mjovr
Fill me in on why? My OS is windows seven, and I have a fresh install of ROR 4.5.0 in Program Files x86. "mods.cache" Doesn't exist in the cache folder. Why is it not there? How come no one else is experiencing this problem? I've also found where when I looked into the RoR.cfg file, Directory names were seemingly cut off by ~1 where the seventh character should be. Is this supposed to be like that?

**Comment by Max98** [comment] 2015-06-29 03:33
Check #228
The problem is fixed in this repo, we just need to upload a new Test Build, which won't happen any time soon for the moment. :P

**Comment by Hiradur** [comment] 2015-06-29 09:37
Use TB2 for the meantime. Sorry for the inconvenience.

**Closed by Hiradur** 2015-06-29 09:37 UTC
Labels: bug, duplicate
