### ISSUE TITLE
Weird Vehicle Behavior. (See Attached Pastebin)

### ISSUE THREAD

**Issue by disloyalpick** [RigsOfRods/rigs-of-rods#1348] opened 2017-07-06 23:29 UTC
https://pastebin.com/3Z29zciL
This is probably the only way to fully undestand what I'm trying to get at with this issue.

It was basically found out that the hydros are causing weird strain.

How to reproduce. Get one of gabester's vehicles. 
Then, start moving slightly. 
Then, turn left or right. Which ever way will make the vehicle start rolling by itself with absolutely no throttle input. 
Then shut the engine off and switch to neutral.
the vehicle will continue to keep rolling.

@L-Tec has been helping me pinpoint the exact issue recently. And Lifter has come to the conclusion that is is definitely hydro related.

If you need any more info like a video of it happening, let me know

**Comment by Michael10055** [comment] 2017-07-06 23:33
Pasting this message here from me on Discord:

> the issue is really noticeable on this vehicle https://forum.rigsofrods.org/thread-102.html which uses a very simple steering setup. it does not happen on 0.3x:
https://gfycat.com/WiltedCheapBarasinga
0.4.7.0+
https://gfycat.com/BraveAchingDrongo

**Comment by only-a-ptr** [comment] 2017-08-25 21:48
I just reproduced it using vehicle https://forum.rigsofrods.org/thread-102.html - it happens when I steer full left while the vehicle had some prior motion.

Weird thing.

**Comment by disloyalpick** [comment] 2017-08-28 00:02
@only-a-ptr Some time ago Lifter helped to tace it down to the hydros causing it to happen. Try sending him a DM about it. He may have a bit more info from his testings.

**Comment by only-a-ptr** [comment] 2018-10-15 11:15
May be related: https://github.com/RigsOfRods/rigs-of-rods/pull/1652

**Comment by tritonas00** [comment] 2019-05-25 15:16
this is probably fixed now, mike and i can't reproduce it anymore

**Closed** 2019-05-25 15:21 UTC
Labels: bug
