### ISSUE TITLE
Trains crashing the game on switch collision meshes

### ISSUE THREAD

**Issue by tgp1994** [RigsOfRods/rigs-of-rods#197] opened 2015-05-19 21:47 UTC
> The bug occurs with trains. When driving over a switch, RoR occasionally crashes without reason. It worked fine in older versions. The problem seems to concern the collision mesh of the train switches. Please notice the Debug information attached here.
**How to reproduce:** Load the map Train Valley. Get into the Henschel train that is placed on the rail. Start the engine, set gearbox to "D" and accelerate with "F6". When you are at the first street crossing, brake with "F5". Drive back to the starting point. Repeat this until the game crashes. Sometimes it appears on second contact with a switch, sometimes it takes more contacts.
**Content needed:** http://www.rigsofrods.com/repository/view/5118, http://www.rigsofrods.com/repository/view/4340

*This was moved from the wiki bug tracker. [Original post.](http://www.rigsofrods.com/threads/111967-Bugtracker-users-we-need-your-help-to-collect-all-bugs!?p=1307247&viewfull=1#post1307247)*

**Comment by skybon** [comment] 2015-06-03 22:10
Duplicate of #160

**Closed by skybon** 2015-06-03 22:10 UTC
Labels: bug, needs confirmation
