### ISSUE TITLE
outdated angelscript API used

### ISSUE THREAD

**Issue by Hubbitus** [RigsOfRods/rigs-of-rods#530] opened 2016-01-06 17:01 UTC
Hello.
I've try add rigsofrods into Fedora distribution, but have error compile recent versions:
```
+ make -j3
/home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/angelscript_addons/contextmgr/contextmgr.cpp: In function 'void AngelScript::ScriptCreateCoRoutine(std::__cxx11::string&, AngelScript::CScriptAny*)':
/home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/angelscript_addons/contextmgr/contextmgr.cpp:68:48: error: 'class AngelScript::asIScriptModule' has no member named 'GetFunctionIdByDecl'
   int funcId = engine->GetModule(mod.c_str())->GetFunctionIdByDecl(decl.c_str());
                                                ^
/home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/angelscript_addons/contextmgr/contextmgr.cpp: In member function 'AngelScript::asIScriptContext* AngelScript::CContextMgr::AddContext(AngelScript::asIScri
ptEngine*, int)':
/home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/angelscript_addons/contextmgr/contextmgr.cpp:247:29: error: invalid conversion from 'int' to 'AngelScript::asIScriptFunction*' [-fpermissive]
  int r = ctx->Prepare(funcId);
                             ^
In file included from /home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/angelscript_addons/contextmgr/contextmgr.h:11:0,
                 from /home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/angelscript_addons/contextmgr/contextmgr.cpp:4:
/usr/include/angelscript.h:877:26: note:   initializing argument 1 of 'virtual int AngelScript::asIScriptContext::Prepare(AngelScript::asIScriptFunction*)'
  virtual int             Prepare(asIScriptFunction *func) = 0;
                          ^
/home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/angelscript_addons/contextmgr/contextmgr.cpp: In member function 'AngelScript::asIScriptContext* AngelScript::CContextMgr::AddContextForCoRoutine(AngelScr
ipt::asIScriptContext*, int)':
/home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/angelscript_addons/contextmgr/contextmgr.cpp:284:31: error: invalid conversion from 'int' to 'AngelScript::asIScriptFunction*' [-fpermissive]
  int r = coctx->Prepare(funcId);
                               ^
In file included from /home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/angelscript_addons/contextmgr/contextmgr.h:11:0,
                 from /home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/angelscript_addons/contextmgr/contextmgr.cpp:4:
/usr/include/angelscript.h:877:26: note:   initializing argument 1 of 'virtual int AngelScript::asIScriptContext::Prepare(AngelScript::asIScriptFunction*)'
  virtual int             Prepare(asIScriptFunction *func) = 0;
                          ^
make[2]: *** [source/angelscript_addons/CMakeFiles/angelscript_addons.dir/contextmgr/contextmgr.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/angelscript_addons/debugger/debugger.cpp: In member function 'virtual void CDebugger::PrintValue(const string&, AngelScript::asIScriptContext*)':
/home/pasha/SOFT/rpmbuild/BUILD/rigs-of-rods-0.4.5.1/source/angelscript_addons/debugger/debugger.cpp:409:60: error: invalid conversion from 'int*' to 'AngelScript::asUINT* {aka unsigned int*}' [-fpermissive]
  asETokenClass t = engine->ParseToken(expr.c_str(), 0, &len);
```

I found that question http://stackoverflow.com/questions/13370774/using-angelscript-compile-error , it seams such API removed completely.

We have 2.30:
$ rpm -q angelscript
angelscript-2.30.2-2.fc23.x86_64

**Comment by Hiradur** [comment] 2016-01-06 17:07
Closing as duplicate of #174 and #441 
Please use 2.22.1 for now

**Closed by Hiradur** 2016-01-06 17:07 UTC

**Comment by Hubbitus** [comment] 2016-01-06 18:21
Unfortunately I can't use other versions than installed in system for users.

**Comment by Hiradur** [comment] 2016-01-06 19:38
I see. I started to update RoR for a newer version of Angelscript a while back but a lot of issues turned up and I eventually lost the motivation to fix them since the error messages weren't exactly descriptive and I've never worked with AS before. Anyway, I'll give it another go soon.

**Comment by disloyalpick** [comment] 2016-01-07 01:13
Maybe you could ask hagdervriese, as it looks like he is pretty good with anglescript based on those maps he made. where the AI actually drives on the road
