### ISSUE TITLE
Improve RoR's graphics

### ISSUE THREAD

**Issue by Max98** [RigsOfRods/rigs-of-rods#221] opened 2015-06-01 15:20 UTC
The first thing a player see in a game is the way it looks. RoR suffers a lot when it comes to graphics, even shadows, something basic, aren't working!
I think that after the 0.4.5 release, we should also try to focus on graphics. A lot of graphical features are broken (Motion blurr/Glow effect..) and others are pretty outdated and are not looking nice (Basic water, DOF, texture shadows..)
Also, Ogre3D has some pretty nice addons, such as SSAO, SkyX and such.. We should try to get them in RoR to make it even better.

**Comment by only-a-ptr** [comment] 2015-06-03 07:04
First thing we should discuss here is upgrading OGRE itself. Currently we're running on 1.8, which is way outdated. The problem is, OGRE has undergone a major upgrade recently and dropped DirectX9 support, which may be a problem for a lot of players here.

To survey the situation, read this news post: http://www.ogre3d.org/2015/02/06/ogre-2-0-rc1-announcement
* OGRE 2.0 uses DirectX9 and is easy to port from 1.8. It has improved performance.
* OGRE 2.1 is about 5x faster than 1.8 and contains HLMS (high-level material system) which is something like "managedmaterials" we have for vehicles - a set of building blocks to compose advanced shaders without programming knowledge. Unfortunately, OGRE 2.1 is DirectX11+ only, and a lot of players around here seem to have problem with that. Needs to be discussed on forums.

Conclusion: 
* We should port to 2.0 as soon as possible, for performance.
* Then we must consider porting to 2.1 with backwards compatibility with 2.0 (for DirectX9, windows-only). The only feasible way to do that is to generate 2 binaries: RoR.exe / RoR_Legacy.exe. Creating one EXE with switchable graphics is a no-go: you can't link one EXE with 2 versions of OGRE (symbol name clashes) so it would require creating some kind of wrapper DLLs for OGRE, which would be super complicated.
* As for OGRE plugins (SkyX...), those are nice but AFAIK incompatible with OGRE 2.1

**Comment by Max98** [comment] 2015-06-03 17:33
I believe that upgrading to 1.9 is something we should do before 2.0, and I think we should do this for next stable, so I can be sure that the PSSM problem is fixed in 1.9.

**Comment by skybon** [comment] 2015-06-03 22:08
@only-a-ptr Isn't OpenGL enough for all platforms?

**Comment by Hiradur** [comment] 2015-06-04 07:29
What about the shader language?

**Comment by only-a-ptr** [comment] 2015-06-04 07:49
@Max98 : IMO we can safely transition to 2.0 directly, but goingh through 1.9 is also fine. Also OK to be done in nextstable.

**Comment by Max98** [comment] 2015-06-04 13:48
Oh, so I will try to go to 2.0 instead.

**Comment by gigapouch** [comment] 2015-08-13 17:44
@skybon OpenGL doesn't really look as good as DirectX and is becoming outdated. :/

**Comment by Hiradur** [comment] 2015-08-14 07:49
@gigapouch can you back this up? Because from what I heard OpenGL offers higher image quality because it isn't overoptimized like D3D. Though you would probably need a magnifier to spot differences.

**Comment by gigapouch** [comment] 2015-08-14 19:18
For example, I have a older bus simulator (2009-10) that uses OpenGL and it just doesn't feel the same as DirectX. Maybe I haven't used any newer programs that use OpenGL.

**Comment by skybon** [comment] 2015-08-14 23:25
@gigapouch "Doesn't feel the same" is hardly an argument. Non-scientific comparisons of Coca Cola and Pepsi Cola taste show advantage of the former while double blind tests reflect 50/50 split.

And be extra careful with the word "optimized" - there's a lot of marketing FUD attached to it. Unless you back this up with hard numbers. Except they prove the reverse.[http://www.phoronix.com/scan.php?page=news_item&px=MTE1NzE]

**Comment by skybon** [comment] 2015-08-14 23:28
This issue is too vague to fit the tracker. Improving game graphics and visual style is always an aspiration for programmers and artists alike. For the report, however, it is better to submit concrete requests with specific ideas and preferably patches.

Closing.

**Closed by skybon** 2015-08-14 23:28 UTC
Labels: enhancement

**Comment by Max98** [comment] 2015-08-16 00:58
Well, I believe that when we will upgrade to Ogre 2.1, graphics will be much better.
