### ISSUE TITLE
alt+up+enter crashes ROR

### ISSUE THREAD

**Issue by jakelyon914** [RigsOfRods/rigs-of-rods#1476] opened 2018-02-24 03:46 UTC
only when in-game, not on menu. I tried to let a truck go at 25% throttle by itself and get out, so i could watch it slowly go over a suspension test. The game crashed, and says "OGRE EXCEPTION(3:RenderingAPIException): Cannot reset device! in D3D9RenderWIndow::reset at D:\ror\dev\dependencies\src\Ogre\ogre_src_v1-9\RenderSystems\Direct3D9\src\OgreD3D9Device.cpp (line 432)"
This is easily repeatable for me and most others, some say shading reloads. One theory was that so much happens at once with the keys, that it crashes low-end PCs. The problem remains even when removing the "EXPL+ALT+RETURN" line from the keymap.

**Comment by AnotherFoxGuy** [comment] 2018-02-24 12:49
Duplicate of #454

**Closed by AnotherFoxGuy** 2018-02-24 12:49 UTC
Labels: duplicate
