### ISSUE TITLE
Multiple spawn points in skinzip style

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#1196] opened 2016-10-20 08:01 UTC
Currently, if you want to add a new spawn point to a map (while you still want to keep the old spawn point) you had to copy and paste the terrn file, change the name and spawn point coordinates. This then adds the terrain many times into the game (while the terrain itself is the same, but the spawn point is different) as seen on Rockton for example.
If it's possible (I'm not coder, so I have no idea if it even is) the skinzip system could be used and converted for terrain needs, so instead of changing textures it'd simply change the coordinates of the spawn point.
This could - as example - be helpful for the Community map project.

**Comment by AnotherFoxGuy** [comment] 2016-10-20 08:31
Duplicate of https://github.com/RigsOfRods/rigs-of-rods/issues/761

**Closed by AnotherFoxGuy** 2016-10-20 08:31 UTC
