### ISSUE TITLE
Compiling on Linux gives an error

### ISSUE THREAD

**Issue by singhamitoj** [RigsOfRods/rigs-of-rods#2676] opened 2021-02-08 16:29 UTC
Hello,
There are problems when I am compiling on Ubuntu 20.10. I am compiling rigs of rods 2020.01. This has never compiled, both on Ubuntu 20.04 and 20.10. I first tried to download the source code from the release page, then using a commit that was made around the release of Rigs of Rods 2020.01. I used git clone, and followed the instructions for compiling.

This is what it spit out the first time I attempted today.

TYPE=Release .
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:15 (project):
No CMAKE_CXX_COMPILER could be found.

Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/amitoj/Desktop/fae7586be7--recursive (copy)/CMakeFiles/CMakeOutput.log".
See also "/home/amitoj/Desktop/fae7586be7--recursive (copy)/CMakeFiles/CMakeError.log".

**Comment by singhamitoj** [comment] 2021-02-08 16:31
This is what it spit out the first time I attempted today.

TYPE=Release .
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:15 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/amitoj/Desktop/fae7586be7--recursive (copy)/CMakeFiles/CMakeOutput.log".
See also "/home/amitoj/Desktop/fae7586be7--recursive (copy)/CMakeFiles/CMakeError.log".

**Comment by tritonas00** [comment] 2021-02-08 17:49
Hi. Any specific reason you don't just use the precompiled linux RoR archive?

**Comment by singhamitoj** [comment] 2021-02-08 18:04
Thank you. I cannot find my Rigs of Rods 2020.01 precompiled package, as I have lost it. I can't find the linux version online, but I can find the windows version on github.

**Comment by tritonas00** [comment] 2021-02-08 18:11
Have tried the new release 2021.02?

**Comment by singhamitoj** [comment] 2021-02-08 18:32
Yes, I have tried the new release. Also, I got stuck on the first step. Running the command above works.

**Comment by singhamitoj** [comment] 2021-02-08 18:33
Never mind, it failed.

-- The CXX compiler identification is GNU 10.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- [pmm] You are using PMM version 1.8.1. The latest is 1.9.0.
-- [pmm] Changes since 1.8.1 include the following:
-- [pmm]  - Changes in 1.9.0:
-- [pmm]     - Added DDS support
-- [pmm]     - Download only used modules
-- [pmm]     - Improved update check
-- [pmm]     - Fixed issue with clang version detection
-- [pmm]     - Added option to turn cmake_multi on/off
-- [pmm] To update, simply change the value of PMM_VERSION_INIT in pmm.cmake
-- [pmm] You can disable these messages by setting PMM_IGNORE_NEW_VERSION to TRUE before including pmm.cmake
-- [pmm] No existing Conan installation found. We'll try to obtain one.
-- [pmm] Get Conan with Python 3
-- [pmm] Get Conan with Python 3 - Candidate Python: /usr/bin/python3.8 
-- [pmm] Get Conan with Python 3 - Create virtualenv
-- [pmm] [warn   ] Error while trying to create virtualenv [1]:
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/amitoj/.local/share/pmm/1.8.1/_conan_venv/bin/python3.8', '-Im', 'ensurepip', '--upgrade', '--default-pip']


-- [pmm] Get Conan with Python 3 - Fail: Could not create virtualenv
CMake Error at _pmm/1.8.1/conan.cmake:633 (message):
  Cannot use Conan with PMM because we were unable to find/obtain a Conan
  executable.
Call Stack (most recent call first):
  _pmm/1.8.1/main.cmake:34 (_pmm_conan)
  _pmm/1.8.1/main.cmake:49 (_pmm_project_fn)
  cmake/DependenciesConfig.cmake:20 (pmm)
  CMakeLists.txt:99 (include)


-- [CMakeCM] Downloading new module cotire.cmake
-- cotire 1.8.1 loaded.
-- CXX target angelscript_addons cotired without unity build.
-- Found Git: /usr/bin/git (found version "2.27.0") 
-- CXX target RoR cotired without unity build.
-- The following OPTIONAL packages have been found:

 * Git

-- The following REQUIRED packages have been found:

 * Threads

-- Configuring incomplete, errors occurred!
See also "/home/amitoj/Downloads/rigs of rods versions/2020.01/rigs-of-rods-2020.01/CMakeFiles/CMakeOutput.log".
See also "/home/amitoj/Downloads/rigs of rods versions/2020.01/rigs-of-rods-2020.01/CMakeFiles/CMakeError.log".

**Comment by singhamitoj** [comment] 2021-02-08 18:33
It failed. I will have to install some dependencies and it might work.

**Comment by tritonas00** [comment] 2021-02-08 18:34
> Also, I got stuck on the first step

With the new release? there is a precompiled archive for that

**Comment by singhamitoj** [comment] 2021-02-08 18:38
No, with 2020.01. Also, it is working now.

**Comment by tritonas00** [comment] 2021-02-08 18:45
> Also, it is working now.

So feel free to close the issue.

**Comment by singhamitoj** [comment] 2021-02-08 18:48
One thing. It failed at the last minute.

ERROR: libalsa/1.1.5@conan/stable: Error in build() method, line 62
	autotools = self._configure_autotools()
while calling '_configure_autotools', line 41
	self.run("libtoolize --force --copy --automake")
	ConanException: Error 127 while executing libtoolize --force --copy --automake
CMake Error at _pmm/1.8.1/conan.cmake:483 (message):
  Conan install failed [1]:

Call Stack (most recent call first):
  _pmm/1.8.1/conan.cmake:519 (_pmm_conan_run_install)
  _pmm/1.8.1/conan.cmake:685 (_pmm_conan_install)
  _pmm/1.8.1/main.cmake:34 (_pmm_conan)
  _pmm/1.8.1/main.cmake:49 (_pmm_project_fn)
  cmake/DependenciesConfig.cmake:20 (pmm)
  CMakeLists.txt:99 (include)


-- Configuring incomplete, errors occurred!
See also "/home/amitoj/Downloads/rigs of rods versions/2020.01/rigs-of-rods-2020.01/CMakeFiles/CMakeOutput.log".
See also "/home/amitoj/Downloads/rigs of rods versions/2020.01/rigs-of-rods-2020.01/CMakeFiles/CMakeError.log".

**Comment by singhamitoj** [comment] 2021-02-08 18:52
It has to do with Conan, but I don't know why. I installed conan before building.

**Comment by tritonas00** [comment] 2021-02-08 19:00
You may want to try https://github.com/tritonas00/ror-dependencies, i use that on Arch
For latest master (2021.02)

```
git clone https://github.com/RigsOfRods/ror-dependencies
cd ror-dependencies
git pull https://github.com/RigsOfRods/ror-dependencies +refs/pull/48/head
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
make -j7
```

then RoR against the ror-dependencies

```
git clone --recursive https://github.com/RigsOfRods/rigs-of-rods
cd rigs-of-rods
cmake -DCMAKE_PREFIX_PATH=/path/to/ror-dependencies/Dependencies_Linux/ -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_PACKAGE_MANAGER=OFF . 
make -j7
make zip_and_copy_resources
```

But whats wrong with 2021.02 and you need 2020.01 (which is not supported anymore)?

**Comment by singhamitoj** [comment] 2021-02-08 20:40
I was just trying to compile the old version for fun.

**Comment by singhamitoj** [comment] 2021-02-08 20:42
Nothing is wrong with 2021.02. I was compiling 2020.01 because I lost the archive. However, 2021.02 is fine as well. I also got error 2 when compiling ror-dependencies.

make: *** [Makefile:84: all] Error 2

**Comment by singhamitoj** [comment] 2021-02-08 20:51
Running make -j7 with verbose doesn't seem to show anything, either.

**Comment by singhamitoj** [comment] 2021-02-08 23:34
I found the archive, but I still don't know why this is happening.

**Comment by tritonas00** [comment] 2021-02-09 03:04
it seems `libalsa/1.1.5` conan package fails to compile on your system, which exactly ubuntu version you use?

**Comment by singhamitoj** [comment] 2021-02-09 12:44
Building the latest version worked.

**Comment by singhamitoj** [comment] 2021-02-09 12:49
Is it the name of the folder?

**Comment by singhamitoj** [comment] 2021-02-09 14:08
It seems like the files cmake was trying to find was not found.

**Comment by singhamitoj** [comment] 2021-02-09 17:28
I tried again with sudo, but that did not work. It still has something to do with conan.

**Comment by singhamitoj** [comment] 2021-02-09 17:34
I'll try compiling without conan.

**Comment by singhamitoj** [comment] 2021-02-09 17:43
-- [pmm] You are using PMM version 1.8.1. The latest is 1.9.0.
-- [pmm] Changes since 1.8.1 include the following:
-- [pmm]  - Changes in 1.9.0:
-- [pmm]     - Added DDS support
-- [pmm]     - Download only used modules
-- [pmm]     - Improved update check
-- [pmm]     - Fixed issue with clang version detection
-- [pmm]     - Added option to turn cmake_multi on/off
-- [pmm] To update, simply change the value of PMM_VERSION_INIT in pmm.cmake
-- [pmm] You can disable these messages by setting PMM_IGNORE_NEW_VERSION to TRUE before including pmm.cmake
-- cotire 1.8.1 loaded.
CMake Error at cmake/DependenciesConfig.cmake:40 (find_package):
  By not providing "FindOGRE.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OGRE", but
  CMake did not find one.

  Could not find a package configuration file provided by "OGRE" (requested
  version 1.11) with any of the following names:

    OGREConfig.cmake
    ogre-config.cmake

  Add the installation prefix of "OGRE" to CMAKE_PREFIX_PATH or set
  "OGRE_DIR" to a directory containing one of the above files.  If "OGRE"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:99 (include)

This is what happened when I tried to compile without conan. I followed the instructions for compiling.

**Comment by singhamitoj** [comment] 2021-02-09 17:48
It seems to be a problem with OGRE.

**Comment by tritonas00** [comment] 2021-02-09 17:50
try conan but disable openal, install it from ubuntu repos, its a runtime only dependency

**Comment by singhamitoj** [comment] 2021-02-09 18:38
How would I do that?

**Comment by tritonas00** [comment] 2021-02-09 18:52
Try removing https://github.com/RigsOfRods/rigs-of-rods/blob/master/conanfile.txt#L14

**Comment by singhamitoj** [comment] 2021-02-09 19:04
I tried that, but I got the same error.

**Comment by tritonas00** [comment] 2021-02-09 19:08
It should work as yesterday https://github.com/RigsOfRods/rigs-of-rods/issues/2676#issuecomment-775361929

remove rigs-of-rdos, .conan and .pmm dirs in your home, and try again with fresh clone

`git clone --recursive https://github.com/RigsOfRods/rigs-of-rods.git`

**Comment by singhamitoj** [comment] 2021-02-09 19:36
I tried doing that, but I still get this:

Could not find a package configuration file provided by "OGRE" (requested
  version 1.11) with any of the following names:

    OGREConfig.cmake
    ogre-config.cmake

I don't know why these files are missing and how I can get them. I used the non-conan compile for this one.

ERROR: libalsa/1.1.5@conan/stable: Error in build() method, line 62
	autotools = self._configure_autotools()
while calling '_configure_autotools', line 41
	self.run("libtoolize --force --copy --automake")
	ConanException: Error 127 while executing libtoolize --force --copy --automake
CMake Error at _pmm/1.8.1/conan.cmake:483 (message):
  Conan install failed [1]:

Call Stack (most recent call first):
  _pmm/1.8.1/conan.cmake:519 (_pmm_conan_run_install)
  _pmm/1.8.1/conan.cmake:685 (_pmm_conan_install)
  _pmm/1.8.1/main.cmake:34 (_pmm_conan)
  _pmm/1.8.1/main.cmake:49 (_pmm_project_fn)
  cmake/DependenciesConfig.cmake:20 (pmm)
  CMakeLists.txt:99 (include)
This one is with conan. Both were fresh clones.

**Comment by tritonas00** [comment] 2021-02-09 19:43
I give up, maybe @AnotherFoxGuy can help with conan stuff

**Comment by singhamitoj** [comment] 2021-02-09 19:47
That's fine, though I seriously don't know why this happened for so long...

**Comment by tritonas00** [comment] 2021-02-09 19:55
because probably its libalsa/1.1.5 problem, not RoR's

**Comment by AnotherFoxGuy** [comment] 2021-02-09 20:04
The only error I see is that cmake can't find a CPP compiler and the libalsa is caused by missing autotools

**Comment by singhamitoj** [comment] 2021-02-09 20:08
Installing autotools with apt on Ubuntu 20.10 says it might have been obsoleted, missing, or available only from another source.
I installed gpp, the C++ compiler I will use.

**Comment by singhamitoj** [comment] 2021-02-09 20:13
However, I do have autotools-dev.

**Comment by singhamitoj** [comment] 2021-02-09 20:25
I am trying to rebuild ror-dependencies.

**Comment by singhamitoj** [comment] 2021-02-09 20:26
So far, it's working!

**Comment by singhamitoj** [comment] 2021-02-09 20:33
How long should the ror-dependencies take to compile?

**Comment by tritonas00** [comment] 2021-02-09 20:37
depending your connection and cpu, needs some time

**Comment by singhamitoj** [comment] 2021-02-09 20:52
Well, I got Error 2 (With no explanation) again.
[CMakeOutput.log](https://github.com/RigsOfRods/rigs-of-rods/files/5954181/CMakeOutput.log)

**Comment by paroj** [comment] 2021-02-12 12:43
you can also try the snap: https://snapcraft.io/rigs-of-rods

**Comment by tritonas00** [comment] 2021-03-13 19:16
closing because its about compiling `2020.01` and

>Building the latest version worked

https://github.com/RigsOfRods/rigs-of-rods/issues/2676#issuecomment-775910174

**Closed by tritonas00** 2021-03-13 19:16 UTC
Labels: Linux, build
