### ISSUE TITLE
sim-monsters.com: Improve handling of mods with missing resources.

### ISSUE THREAD

**Issue by only-a-ptr** [RigsOfRods/rigs-of-rods#461] opened 2015-11-30 12:40 UTC
Regarding this forum thread: http://www.rigsofrods.com/threads/120664-Are-older-versoins-avalible

Needs further investigation.

**Comment by Hiradur** [comment] 2015-11-30 13:25
I think it's the same as https://github.com/RigsOfRods/rigs-of-rods/issues/373

**Comment by DirtGamer301** [comment] 2015-11-30 14:39
I'm not sure, but I think many of the vehicles downloadable there don't seem to work in any 0.4 version so it might not be a 0.4.5.1 specific thing. It's also said that people monster trucking together in RoR multiplayer always use 0.37, so that might be why he was told to get this version.

**Comment by Aivar-RoR** [comment] 2015-11-30 18:14
So I downloaded a few trucks from the site. 
This one: http://sim-monsters.com/index.php?/topic/5805-v4-custombad-habit-trophy-truck-custom/
The other one was this: http://sim-monsters.com/index.php?/topic/9287-v4-replicamadusa-2015-madusa-wfxvi/
To rule out any issues in 0.4.5.1, I tried both vehicles in 0.39.5. It seems that the spawning problems aren't caused by bugs in RoR. The authors haven't included all the dependencies in their .zip files, therefore the trucks cause a crash. 
For example, the BadHabitTrophy.truck.
RoR crashed because a flare material was not found:
`OGRE EXCEPTION(5:ItemIdentityException): Could not find material GraveDiggerredflare in BillboardSet::setMaterialName at C:\data\ror-trunk\dependencies\src\Ogre\ogre_src_v1-7-3\OgreMain\src\OgreBillboardSet.cpp (line 312)`

Commented out the flare, another error popped up that crashed RoR:

`OGRE EXCEPTION(5:ItemIdentityException): Unable to derive resource group for SIR4wsouter.mesh automatically since the resource was not found. in ResourceGroupManager::findGroupContainingResource at C:\data\ror-trunk\dependencies\src\Ogre\ogre_src_v1-7-3\OgreMain\src\OgreResourceGroupManager.cpp (line 1782)`

Commented out the 4 mesh files, another error that crashed RoR:

`OGRE EXCEPTION(5:ItemIdentityException): Unable to derive resource group for OR4wsLower.mesh automatically since the resource was not found. in ResourceGroupManager::findGroupContainingResource at C:\data\ror-trunk\dependencies\src\Ogre\ogre_src_v1-7-3\OgreMain\src\OgreResourceGroupManager.cpp (line 1782)`

Commented out the 2 mesh files, another error that crashed RoR:

`OGRE EXCEPTION(5:ItemIdentityException): Unable to derive resource group for OrangeDshaft.mesh automatically since the resource was not found. in ResourceGroupManager::findGroupContainingResource at C:\data\ror-trunk\dependencies\src\Ogre\ogre_src_v1-7-3\OgreMain\src\OgreResourceGroupManager.cpp (line 1782)`

Fearing to get stuck in an endless loop I stopped. 
Checked the log and found some more errors:

`BIO|ERROR |BadHabitTrophy.truck:0012 | globals | Material 'GravediggerBand' used in Section 'globals' not found! We will try to use the material 'tracks/transred' instead.
Can't assign material GravediggerBand to SubEntity of wheelobj-t32-0 because this Material does not exist. Have you forgotten to define it in a .material script?`

`OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource Chassis_Colors.png in resource group General-Reloaded-2 or any other group. in ResourceGroupManager::openResource at C:\data\ror-trunk\dependencies\src\Ogre\ogre_src_v1-7-3\OgreMain\src\OgreResourceGroupManager.cpp (line 753)`

`Error loading texture Chassis_Colors.png. Texture layer will be blank. Loading the texture failed with the following exception: OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource Chassis_Colors.png in resource group General-Reloaded-2 or any other group. in ResourceGroupManager::openResource at C:\data\ror-trunk\dependencies\src\Ogre\ogre_src_v1-7-3\OgreMain\src\OgreResourceGroupManager.cpp (line 753)`

`OGRE EXCEPTION(6:FileNotFoundException): Cannot locate resource rkmradiator.png in resource group General-Reloaded-2 or any other group. in ResourceGroupManager::openResource at C:\data\ror-trunk\dependencies\src\Ogre\ogre_src_v1-7-3\OgreMain\src\OgreResourceGroupManager.cpp (line 753)`

`etc . . . `
Will not waste space posting all the errors (very many missing textures).
Noticed similar issues with the other vehicle.

So the issues happen because of **messy modding practice**.

**Comment by only-a-ptr** [comment] 2015-12-01 14:07
@Aivar-RoR Thanks for investigation.

Unfortunately, due to lack of proper tools and fault-ignorance of pre-0.4.5 parser, most trucks are messy. But we're stuck with them, so we need to handle them the best we can.

Missing resources should never crash RoR. If they're critical, they should only cancel the loading, showing an error dialog like "Spawning failed; critical errors in the vehicle. See spawner log". If the resources are non-critical, the vehicle should load anyway with a warning dialog "Missing resources in the vehicle, it may not look correctly. See spawner log."

**Comment by Hotrod55** [comment] 2015-12-02 01:43
How would the parser know if a prop/flexbody is "critical"? Unless it's going to detect keywords or be a special section in the .truck file I don't see how it's going to work.

**Comment by only-a-ptr** [comment] 2015-12-02 11:59
@Hotrod55 By "critical", I meant "affecting vehicle's behavior". To be honest, I'm not even sure if there are any such capabilities, I'm not a modder.

For sure, any prop/flexbody is non-critical because it's only eye-candy, it has no effect on collision or handling. The worst thing that can happen is having an invisible vehicle (remember, we're talking about messy truckfiles). Similarily, any texture or material is non-critical. Airfoils, for example, are questionable.

**Comment by Max98** [comment] 2015-12-06 09:03
@Aivar-RoR I'm not sure, but can you download Box5Diesel's monster pack, and merge it into that zip, and try again?

**Comment by Hotrod55** [comment] 2015-12-06 16:29
Most content on Sim-Monsters has to be merged into the V4 pack found [here] (http://sim-monsters.com/index.php?/files/file/1399-sim-monsters-v4-038-compatible/) 
The pack has over 200 trucks and is over 600mb, which can be very annoying for people who have slow internet connections or do not want their vehicle selector to be flooded with the same type of vehicle.
Some of the newer content doesn't need to be extracted however and is standalone, for [example] (http://sim-monsters.com/index.php?/files/file/1961-heartbeat/).

**Comment by tritonas00** [comment] 2019-05-30 12:40
i think this is fixed now by https://github.com/RigsOfRods/rigs-of-rods/pull/1214

**Comment by CuriousMike56** [comment] 2020-04-15 14:35
This can be closed now. Mods with missing assets no longer crash and all new SM trucks are standalone now.

**Closed** 2020-04-15 15:35 UTC
Labels: enhancement
