### ISSUE TITLE
"Flying" Vehicles

### ISSUE THREAD

**Issue by AnotherFoxGuy** [RigsOfRods/rigs-of-rods#1131] opened 2016-09-22 10:06 UTC
**Steps to reproduce**
- Spawn a vehicle on [mt everest](https://github.com/RigsOfRods/rigs-of-rods/files/486953/mt.everest.zip)
- The terrain collisions will be offset by ~1 meter.

**Screenshot**
![screenshot_2016-09-22_12-00-51_1](https://cloud.githubusercontent.com/assets/9480940/18744054/8166be52-80bc-11e6-9658-ccf54e804176.png)

**Comment by ulteq** [comment] 2016-10-01 21:38
Do you know any RoR version without this bug?

**Comment by AnotherFoxGuy** [comment] 2016-10-02 07:19
@ulteq I think this commit broke it: https://github.com/RigsOfRods/rigs-of-rods/commit/a8b8267eab7bfa235d54c14fd0e171e4939ce33b

**Comment by ulteq** [comment] 2016-10-07 19:18
> I think this commit broke it: a8b8267

I can reproduce the bug without this commit applied.

> The terrain collisions will be offset by ~1 meter.

The terrain collision seems to only be off in front of the hangar.

**Comment by AnimosusTheWolf** [comment] 2016-10-10 17:38
This terrain acts very odd in 0.38.37 as well, like you're stuck in objects. For some reason none of the objects in the .tobj file are spawning other than the truck depot and hanger. But there is collision for them it seems.

**Comment by ulteq** [comment] 2016-10-11 07:43
I vote to close this then.

**Comment by Michael10055** [comment] 2016-10-12 20:22
The other objects (runway objects) spawn fine:
![screenshot_2016-10-12_16-19-00_1](https://cloud.githubusercontent.com/assets/11002490/19326316/05c5f8da-9098-11e6-8215-7a55c2a84894.png)

**Comment by ulteq** [comment] 2016-10-18 09:35
Might be the same issue: https://gitter.im/RigsOfRods/rigs-of-rods?at=5805a050b827179842cfb5a1

**Comment by tritonas00** [comment] 2018-10-17 18:52
its not only vehicles on that map
you can see the rorbot also "flying"

**Comment by CuriousMike56** [comment] 2019-06-16 04:27
This is also very apparent with [MudFest](https://forum.rigsofrods.org/resources/mudfest.547/):
(Screenshots from 4x4convoy)
![image](https://user-images.githubusercontent.com/46073351/59559031-6067e500-8fcd-11e9-9407-88da70d36124.png)
![image](https://user-images.githubusercontent.com/46073351/59559034-6c53a700-8fcd-11e9-931d-2faad662ff7b.png)
![image](https://user-images.githubusercontent.com/46073351/59559037-72e21e80-8fcd-11e9-8549-5959716579f7.png)

**Comment by only-a-ptr** [comment] 2023-07-09 14:03
Just tested in latest master - still happens.

Though it's clearly not a bug but simply an edge case in the terrain system - the vertical scale of the heightmap is simply so steep that OGRE's smoothing algorithm breaks and the mesh doesn't match the reported height anymore. Some tweaks may help but ultimately it's a content issue, not a game bug.

**Closed by only-a-ptr** 2023-07-09 14:03 UTC
Labels: bug
