### ISSUE TITLE
Missing material

### ISSUE THREAD

**Issue by wilkgr76** [RigsOfRods/rigs-of-rods#1322] opened 2017-04-21 06:05 UTC
AppVeyor build (downloaded 21/04/2017, not sure when the build itself was)

A vehicle which worked in previous versions of RoR, the Bobcat S130, now has stealth mode engaged permernantly:
![screenshot_2017-04-21_14-39-08_1](https://cloud.githubusercontent.com/assets/12093476/25264739/3974d700-26ac-11e7-82af-7a91289d0fcf.png)

Spawner log:
>   == Parsing done, report:
> 
>  WARNING  (Section wheels)
> 	Line (813): -35
> 	Message: Encountered node with illegal negative number: '-35', parsing as positive '35' for backwards compatibility. Please fix as soon as possible.
>  WARNING  (Section wheels)
> 	Line (815): -34
> 	Message: Encountered node with illegal negative number: '-34', parsing as positive '34' for backwards compatibility. Please fix as soon as possible.
> 
> 
>  == Validating done OK
> 
>  ERROR (Keyword ~Unknown~)
> 	Material 'CabMeshMaterial_1@Actor_1' missing!

**Comment by Michael10055** [comment] 2017-04-21 19:23
I can't reproduce this on the latest master (https://github.com/RigsOfRods/rigs-of-rods/commit/aa7db6d4416a5aa81ab492780490ea83c0f83d0f):
![screenshot_2017-04-21_15-20-45_1](https://cloud.githubusercontent.com/assets/11002490/25292941/6b534f78-26a6-11e7-8dac-ab5047a7a183.png)

**Comment by only-a-ptr** [comment] 2017-04-21 21:07
@Michael10055 That's a build of my WIP PullRequest https://github.com/RigsOfRods/rigs-of-rods/pull/1271

The indication is the material name "CabMeshMaterial_1@Actor_1" - it's a scheme I'm putting to use just now.

**Comment by only-a-ptr** [comment] 2017-04-21 21:08
@wilkgr76 Thanks for testing, but there's a reason the PullRequest is titled "alpha1". It's incomplete and bound to crash. I'm closing this ticket.

**Closed by only-a-ptr** 2017-04-21 21:08 UTC

**Comment by wilkgr76** [comment] 2017-04-22 00:15
@only-a-ptr Ooops didn't notice - I apologise.
