### ISSUE TITLE
Support for linux ARM64 builds.

### ISSUE THREAD

**Issue by HanoJing** [RigsOfRods/rigs-of-rods#3061] opened 2023-06-22 13:23 UTC
Hey all, 

Are there builds for Linux ARM64 planned for the future?
I own a powerful ARM64 desktop, I can help with testing and feedback if you want me to.

Many thanks!

**Comment by CuriousMike56** [comment] 2023-06-22 14:23
Duplicate of #3051

**Closed** 2023-06-22 14:27 UTC
