### ISSUE TITLE
Avast! blocks new RoR test build before download finishes

### ISSUE THREAD

**Issue by gigapouch** [RigsOfRods/rigs-of-rods#368] opened 2015-08-07 23:29 UTC
Why does Avast think that RoR is a virus?

**Comment by Max98** [comment] 2015-08-08 09:18
Does this happen using the updater?

**Comment by Hiradur** [comment] 2015-08-08 09:53
Are you sure it's not warning about a flash animation instead?

**Comment by Max98** [comment] 2015-08-08 11:55
@Hiradur No it's not, other avast users are experiencing the same thing.

**Comment by skybon** [comment] 2015-08-08 16:00
Duplicate of #366.

**Closed by skybon** 2015-08-08 16:00 UTC
