### ISSUE TITLE
Terrain shininess should be reduced.

### ISSUE THREAD

**Issue by Erie-E8** [RigsOfRods/rigs-of-rods#315] opened 2015-07-20 16:17 UTC
Someone should figure out how to reduce the specular shininess of terrains. It's more of an annoyance than an issue, but, I just thought I'd throw it in.

**Comment by Speciesx** [comment] 2015-07-20 16:29
a example terrain?

**Comment by Erie-E8** [comment] 2015-07-20 16:31
N Helens is shiny, I think Baker Ranch is.

**Comment by Speciesx** [comment] 2015-07-20 16:40
not really
![78c22342-2e13-11e5-97ac-5af039f9c309](https://cloud.githubusercontent.com/assets/1196375/8781349/bc15ec4a-2f0e-11e5-85ad-6b41e7af2e45.png)

**Comment by Erie-E8** [comment] 2015-07-20 16:41
Still a bit too bright, specular wise.

**Comment by Speciesx** [comment] 2015-07-20 16:46
This caused by caelum.

**Comment by Erie-E8** [comment] 2015-07-20 16:49
Oh. Is there any way to reduce the specular effect?

**Comment by Speciesx** [comment] 2015-07-20 16:53
edit the RoRSkies.os

**Comment by Erie-E8** [comment] 2015-07-20 16:54
Ok.

**Comment by gigapouch** [comment] 2015-07-28 19:51
@Speciesx Did you get nhelens to the normal color in 0.4.5?

**Comment by Hiradur** [comment] 2015-07-29 08:04
@gigapouch He did, see https://github.com/RigsOfRods/rigs-of-rods/issues/174

**Comment by Hiradur** [comment] 2015-10-24 17:47
Closing as 3rd party content bug. If you disagree, reopen with examples.

**Closed by Hiradur** 2015-10-24 17:47 UTC
Labels: enhancement, needs discussion
