### ISSUE TITLE
Re-Add Multiplayer Collisions

### ISSUE THREAD

**Issue by derbymutt** [RigsOfRods/rigs-of-rods#982] opened 2016-05-24 19:09 UTC
Years ago, Rigs of Rods had multiplayer collisions. They were removed for some reason.

A year or two ago there was a 0.38.67 client that had online collisions. Since the RoRnet is being advanced forward finally, why not add them back?

This could be done by each client locally checking for collisions on their local version of other player's trucks submeshes and contacters using a similar system to how local collisions are done, and possibly just assuming other player's vehicles are a solid wall.

The gitter chat on the topic:

> ulteq @ulteq 14:54
> I would probably do multiplayer collisions by having all colliding trucks be simulated on the pc with the best internet connection.
> And just stream the keyboard / mouse input from the other pc.
> hence the old drive another player's de-synced car bug?
> Yes, it's really just a flag that tells a client that he doesn't own a truck.
> 
> Alex Scheiner @derbymutt 14:55
> why not do it how it was before? and have the clients just use their local version of the vehicle's submesh and contacters?
> that worked somewhat well before
> 
> ulteq @ulteq 14:55
> I never played that version.
> 
> Alex Scheiner @derbymutt 14:55
> and the pc with the best connection may not be fast enough to simulate the collisions
> 
> ulteq @ulteq 14:56
> You could make it configurable who simulates it.
> Which version had multiplayer collisions?
> 
> Alex Scheiner @derbymutt 14:56
> at some point there was a 0.38.67 client compiled that had collisions working in the way I described
> 0.33d may have had collisions
> 
> ulteq @ulteq 14:56
> have the clients just use their local version of the vehicle's submesh and contacters
> I don't really understand what you mean.
> 
> Alex Scheiner @derbymutt 14:57
> since the client already loads the .truck files, why not use the current system for local collisions and check for non-owned trucks as well?
> 
> ulteq @ulteq 14:58
> And what do you do with the forces that act on the remote truck?
> Ignore them?
> 
> Alex Scheiner @derbymutt 14:58
> basically treat the other player's vehicle as a solid wall
> 
> ulteq @ulteq 14:59
> Yeah, that's possible.
> Could be made a RoR.cfg option for those who actually like it.
> 
> Alex Scheiner @derbymutt 14:59
> since both players would be contacting each other remotely it would appear to be a logical impact to both of them
> having it as a configuration option would be fine
> though that would get interesting when someone disabled it and drove straight through another player
> 
> ulteq @ulteq 15:01
> Yeah, 
> 
> Alex Scheiner @derbymutt 15:02
> its not a perfect system, but it would be a start
> 
> ulteq @ulteq 15:02
> Can you make a github issue for it?
> So we don't forget about it.
> We can also discuss there if and how to implement it.
> 
> Sean @Dogy144 15:02
> another idea would be to make it a server controlled option. As in if the server allows collisions or not
> 
> ulteq @ulteq 15:03
> Yeah, that would probably make more sense.
> 
> tritonas00 @tritonas00 15:03
> another idea would be to make it a server controlled option. As in if the server allows collisions or not
>

**Comment by Hiradur** [comment] 2016-05-24 19:24
I think I read about multiplayer collisions in the changelog of 0.36.2.

> And just stream the keyboard / mouse input from the other pc.

Not sure if that would work well. It would definitely feel unresponsive for everybody except the host even with low latency connections (from my experience ~8ms of input lag is noticeable) and what if some packets get lost?

**Comment by ulteq** [comment] 2016-05-24 20:14
> Not sure if that would work well. 

I don't know either. But that's probably the least complicated way of doing it.

**Comment by ulteq** [comment] 2016-05-24 20:16
> Not sure if that would work well.

Probably not.

**Comment by ulteq** [comment] 2016-05-27 12:08
Duplicate of https://github.com/RigsOfRods/rigs-of-rods/issues/183

**Closed by ulteq** 2016-05-27 12:08 UTC
Labels: duplicate, enhancement, multiplayer, request
