### ISSUE TITLE
VY/VX node not found flexbody error -> crash

### ISSUE THREAD

**Issue by Michael10055** [RigsOfRods/rigs-of-rods#1058] opened 2016-06-20 16:39 UTC
If you have a flexbody line with invalid forsets, the game will just crash with this line in the log:
```
12:29:55: FLEXBODY ERROR on mesh BK_73Suburban_RBump.mesh: VX node not found
```
In a older build I have (68f5b34), the error is ignored, Unfortunately I don't know of any released mods that have this error.

**Comment by ulteq** [comment] 2016-10-07 07:49
Needs to be retested one this one is merged: https://github.com/RigsOfRods/rigs-of-rods/pull/1137

**Comment by Michael10055** [comment] 2016-10-12 03:00
Still crashes on the latest upstream.

**Comment by AnotherFoxGuy** [comment] 2016-10-12 07:11
Id: 90    | Current: Yes    | StackSize: 20  
---|---|---  
Function | File(Line)  
**OgreMain** | ** \- **  
RoR!FlexBody::FlexBody | f:/rigs-of-rods/source/main/physics/flex/flexbody.cpp(560)  
RoR!RoR::FlexFactory::CreateFlexBody | f:/rigs-of-rods/source/main/physics/flex/flexfactory.cpp(88)  
RoR!RigSpawner::ProcessFlexbody | f:/rigs-of-rods/source/main/physics/rigspawner.cpp(1868)  
RoR!RigSpawner::SpawnRig| f:/rigs-of-rods/source/main/physics/rigspawner_processcontrol.cpp(16707566)  
RoR!Beam::LoadTruck | f:/rigs-of-rods/source/main/physics/beam.cpp(5756)  
RoR!Beam::Beam | f:/rigs-of-rods/source/main/physics/beam.cpp(5468)  
RoR!BeamFactory::CreateLocalRigInstance | f:/rigs-of-rods/source/main/physics/beamfactory.cpp(215)  
RoR!RoRFrameListener::updateEvents | f:/rigs-of-rods/source/main/gameplay/rorframelistener.cpp(1308)  
RoR!RoRFrameListener::frameStarted | f:/rigs-of-rods/source/main/gameplay/rorframelistener.cpp(1571)  
OgreMain |  \-   
OgreMain |  \-   
RoR!RoR::MainThread::EnterGameplayLoop | f:/rigs-of-rods/source/main/mainthread.cpp(862)  
RoR!RoR::MainThread::Go | f:/rigs-of-rods/source/main/mainthread.cpp(439)  
RoR!main | f:/rigs-of-rods/source/main/main.cpp(250)  
RoR!WinMain | f:/rigs-of-rods/source/main/main.cpp(256)  
RoR!__scrt_common_main_seh | f:/dd/vctools/crt/vcstartup/src/startup/exe_common.inl(253)  
kernel32!BaseThreadInitThunk |  \-   
ntdll!__RtlUserThreadStart |  \-   
ntdll!_RtlUserThreadStart |  \-

**Comment by tritonas00** [comment] 2016-10-12 13:18
> Still crashes on the latest upstream.

Liebherr-630-ECH seems to work here

![2016-10-12-161715_1366x768_scrot](https://cloud.githubusercontent.com/assets/2660424/19311525/79cb00dc-9097-11e6-9780-b5a600010103.png)

**Comment by AnotherFoxGuy** [comment] 2016-10-22 11:17
I think the VY/VX node not found flexbody crash is caused by this: 
https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/physics/flex/FlexBody.cpp#L550-L558

If the VY node isn't found the value gets set to ```-1``` and after that the game tries to get the value of ```m_nodes[-1]```

**Closed** 2016-10-22 12:11 UTC
Labels: bug, coding
