### ISSUE TITLE
Direct3D11 & GL3Plus fails on terrain load

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1993] opened 2018-12-27 21:27 UTC
https://github.com/MyGUI/mygui/tree/master/Media/MyGUI_Media
Add the missing files MyGUI_VP.glsl, MyGUI_VP.hlsl,MyGUI_FP.glsl and MyGUI_FP.hlsl to resources\mygui

I get the same error with Direct3D11 or GL3Plus 
![dx11](https://user-images.githubusercontent.com/1196375/50494644-d7f88680-0a24-11e9-9616-05fe1ef6cd30.JPG)

Possible solution: https://forums.ogre3d.org/viewtopic.php?t=94079

**Comment by Speciesx** [comment] 2018-12-27 23:37
my bad, i've used the the latest mygui master.

**Comment by AnotherFoxGuy** [comment] 2018-12-28 10:35
Duplicate of #491

**Closed by AnotherFoxGuy** 2018-12-28 10:35 UTC
Labels: bug
