### ISSUE TITLE
Managedmaterials Double-Sided Option Broken

### ISSUE THREAD

**Issue by graysonk95** [RigsOfRods/rigs-of-rods#436] opened 2015-09-07 13:10 UTC
"set_managedmaterials_options 1" does not work as of 0.4.5.1.
Any material using this option appears single-sided (ie: it has an invisible backface).

(You should not be able to see pure daylight from inside the bus, the "glass" material should be double-sided).
![screenshot_492e](https://cloud.githubusercontent.com/assets/10550037/9717283/643e5b68-553f-11e5-8fdd-2af8a4571f8f.png)

**Comment by DirtGamer301** [comment] 2015-09-07 13:46
Duplication of https://github.com/RigsOfRods/rigs-of-rods/issues/323

**Comment by Hiradur** [comment] 2015-09-12 16:15
Closing as duplicate of #323 

@graysonk95 Can you post your screenshots in #323 as they are a good representation of the problem?

**Closed by Hiradur** 2015-09-12 16:15 UTC
