### ISSUE TITLE
Lotus Esprit collapses on itself on spawn

### ISSUE THREAD

**Issue by AviorTV** [RigsOfRods/rigs-of-rods#1306] opened 2017-03-29 19:29 UTC
Whenever I spawn a Lotus Esprit, the car collapses on itself. This bug
 occurs from 0.4.5.
Here are the screenshots:
![screenshot_2017-03-29_21-14-47_1](https://cloud.githubusercontent.com/assets/18293938/24472518/4b2b51c4-14c6-11e7-90a7-34cdc7ae6457.png)
![screenshot_2017-03-29_21-15-26_1](https://cloud.githubusercontent.com/assets/18293938/24472550/6792efd4-14c6-11e7-820c-119bbbb2c70e.png)
![screenshot_2017-03-29_21-15-37_1](https://cloud.githubusercontent.com/assets/18293938/24472551/67954cca-14c6-11e7-983a-2cd53b41f508.png)

And here's the download link: http://www.mediafire.com/?ka4uruepf2ko4uo

**Comment by Speciesx** [comment] 2017-03-29 20:14
```
22:04:58:  ===== LOADING VEHICLE: LotusEsprit_JB.truck
22:04:58:  == Parsing vehicle file: LotusEsprit_JB.truck
22:04:58:  == Parsing done, report:

#FFFF00 WARNING #FFFFFF (Section nodes2)
	Line (103): set_node_defaults -1, 1.0, -1, -1
	Message: Parsed data for verification:
	LoadWeight: -1
	  Friction: 1
	    Volume: -1
	   Surface: -1
	   Options: 
#FFFF00 WARNING #FFFFFF (Section nodes2)
	Line (110): set_node_defaults -1, 1.0, 2.0, -1
	Message: Parsed data for verification:
	LoadWeight: -1
	  Friction: 1
	    Volume: 2
	   Surface: -1
	   Options: 
#FFFF00 WARNING #FFFFFF (Section meshwheels2)
	Line (418): set_node_defaults -1, 0.00, -1, -1
	Message: Parsed data for verification:
	LoadWeight: -1
	  Friction: 0
	    Volume: -1
	   Surface: -1
	   Options: 
#FFFF00 WARNING #FFFFFF (Section nodes)
	Line (426): set_node_defaults -1, 1.00, -1, -1
	Message: Parsed data for verification:
	LoadWeight: -1
	  Friction: 1
	    Volume: -1
	   Surface: -1
	   Options: 
#FFFF00 WARNING #FFFFFF (Section beams)
	Line (974): 354,53, is 5.0
	Message: Integer argument [4] has invalid trailing characters
#FFFF00 WARNING #FFFFFF (Section beams)
	Line (975): 357,90, is 2.0
	Message: Integer argument [4] has invalid trailing characters
#FFFF00 WARNING #FFFFFF (Section beams)
	Line (976): 357,55, is 5.0
	Message: Integer argument [4] has invalid trailing characters
#FFFF00 WARNING #FFFFFF (Section beams)
	Line (977): 357,53, is 5.0
	Message: Integer argument [4] has invalid trailing characters
#FFFF00 WARNING #FFFFFF (Section beams)
	Line (978): 360,53, is 5.0
	Message: Integer argument [4] has invalid trailing characters
#FFFF00 WARNING #FFFFFF (Section beams)
	Line (980): 368,56, is 5.0
	Message: Integer argument [4] has invalid trailing characters
#FFFF00 WARNING #FFFFFF (Section beams)
	Line (981): 371,97, is 2.0
	Message: Integer argument [4] has invalid trailing characters
#FFFF00 WARNING #FFFFFF (Section beams)
	Line (982): 371,54, is 5.0
	Message: Integer argument [4] has invalid trailing characters
#FFFF00 WARNING #FFFFFF (Section beams)
	Line (983): 371,56, is 5.0
	Message: Integer argument [4] has invalid trailing characters
#FFFF00 WARNING #FFFFFF (Section beams)
	Line (984): 374,54, is 5.0
	Message: Integer argument [4] has invalid trailing characters
#FFFF00 WARNING #FFFFFF (Section shocks)
	Line (2925): set_node_defaults -1, 0.99, -1, -1
	Message: Parsed data for verification:
	LoadWeight: -1
	  Friction: 0.99
	    Volume: -1
	   Surface: -1
	   Options: 
#FFFF00 WARNING #FFFFFF (Section commands2)
	Line (3007): set_node_defaults -1, -1, -1, -1
	Message: Parsed data for verification:
	LoadWeight: -1
	  Friction: -1
	    Volume: -1
	   Surface: -1
	   Options: 
#FFFF00 WARNING #FFFFFF (Section commands2)
	Line (3011): set_node_defaults -1, 0.99, -1, -1
	Message: Parsed data for verification:
	LoadWeight: -1
	  Friction: 0.99
	    Volume: -1
	   Surface: -1
	   Options: 
#FFFF00 WARNING #FFFFFF (Section meshwheels2)
	Line (3020): set_node_defaults -1, 1.0, -1, -1
	Message: Parsed data for verification:
	LoadWeight: -1
	  Friction: 1
	    Volume: -1
	   Surface: -1
	   Options: 
#FFFF00 WARNING #FFFFFF (Section meshwheels2)
	Line (3034): set_node_defaults -1, 1.14, -1, -1
	Message: Parsed data for verification:
	LoadWeight: -1
	  Friction: 1.14
	    Volume: -1
	   Surface: -1
	   Options: 
#FFFF00 WARNING #FFFFFF (Section meshwheels2)
	Line (3071): set_node_defaults -1, 1.14, -1, -1
	Message: Parsed data for verification:
	LoadWeight: -1
	  Friction: 1.14
	    Volume: -1
	   Surface: -1
	   Options: 

```

**Comment by AnotherFoxGuy** [comment] 2017-03-30 07:57
Duplicate of #171

**Closed by AnotherFoxGuy** 2017-03-30 07:57 UTC
Labels: duplicate
