### ISSUE TITLE
[RoRnet 2.40] timeout shouldn't shut down ror

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#1279] opened 2017-02-16 18:52 UTC
>19:41:17: [RoR|Globals] Updating "mp_server_port": [12013] => [12015]
19:41:17: [RoR|Networking] Trying to join server 'ror.avrintech.net' on port 12015'...
19:41:27: NET receive error 1: SWBaseSocket::waitIO() timeout

Tried to connect to ror.avrintech.net rornet 2.40 server, but after few seconds ror close without a error.

**Comment by only-a-ptr** [comment] 2017-02-21 17:30
Is the `19:41:27: NET receive error 1: SWBaseSocket::waitIO() timeout` the last line in RoR.log? If yes, then I suspect the shutdown didn't come from RoR, but the SocketW library instead.

I need to test myself. I thought I already removed all the shutdowns.

**Comment by tritonas00** [comment] 2017-09-30 17:21
Still valid

**Comment by only-a-ptr** [comment] 2017-10-17 06:55
@tritonas00 😟 Thanks for reminding me.

**Comment by only-a-ptr** [comment] 2019-08-09 17:12
Is this still valid?

**Comment by tritonas00** [comment] 2019-08-09 17:18
i cant reproduce it

i tried even cutting the internet while RoR connects, no still issue.

i suggest close it unteil we can reproduce it again

**Comment by only-a-ptr** [comment] 2019-08-13 13:23
Closing until further notice 🙂

**Comment by tritonas00** [comment] 2022-03-17 18:18
Still valid

**Comment by only-a-ptr** [comment] 2022-03-17 18:24
Applying this https://github.com/RigsOfRods/ror-server/commit/b455cec7a69745b7c854c4d701556a2e57d8a615 to SocketW dependency should fix it.

**Closed** 2022-03-18 09:24 UTC
Labels: bug
