### ISSUE TITLE
Cache regeneration performance issues

### ISSUE THREAD

**Issue by DirtGamer301** [RigsOfRods/rigs-of-rods#238] opened 2015-06-06 13:21 UTC
Regenerating the cache in Test Build 3 is waaay slower than in 0.4.0.7.

Also, after regenerating cache manually in 0.4.5.0 every single vehicle will be in the "Fresh" section.

**Comment by DirtGamer301** [comment] 2015-06-06 20:56
Update/edit:

I tested it again and only noticed a performance issue when manually regenerating cache via RoRConfig.exe.
If you install a new/delete a mod and NextStable automatically regenerates cache there are no performance differences.

**Comment by only-a-ptr** [comment] 2015-06-12 09:52
@DirtGamer301 : Try manually erasing the content of Rigs of Rods 0.4/cache directory, then repeat your tests. I think you mixed 2 distinct operations:
1. Full cache re-generation (RoR config erased cache and launched RoR to regen it)
2. Incremental (read "partial") update (when you add/remove a mod)

**Comment by DirtGamer301** [comment] 2015-06-12 15:13
I've always pressed on "regen cache", not clear cache, for test 1 and add/removing a vehicle for test 2 as cache clearing takes hours (atleast for me).

**Comment by DODGEcharger** [comment] 2015-07-20 16:24
I haven't noticed any difference in performance between cache regeneration in TB4 and previous versions. If anything I'd say TB4 is a bit quicker at regenerating. :P

**Comment by derbymutt** [comment] 2015-07-21 14:14
TB4 is much slower than .4.0.7 at regenning the cache (takes about 10 seconds per mod rather than the 20 or so mods per second in .4.0.7), and usually ends up crashing out for me about 1/4 of the way through, forcing me to regen in .4.0.7.

**Comment by Max98** [comment] 2015-07-21 19:28
@only-a-ptr The problem is that the new parser actually reads the whole truck file instead of just the sections needed for the cache.(Eg. title, description.. not nodes & beams and stuff) Which results in a slower regen time.

**Comment by Olius** [comment] 2015-07-21 23:05
For me, clicking "clear cache" in the configurator and then launching RoR take around 1~2 mins with 147 mods (the HQ and Content packs for 0.4 and a couple other vehicles). It's definitely slower than 0.4.0.7, but it's far from taking hours for me.

**Comment by only-a-ptr** [comment] 2015-07-22 17:21
I'll implement a "metadata-only" mode to the parser so that it only reads useful info and works faster.

**Comment by AnotherFoxGuy** [comment] 2017-03-28 09:51
@only-a-ptr Is this fixed with https://github.com/RigsOfRods/rigs-of-rods/pull/1233 ?

**Comment by only-a-ptr** [comment] 2017-03-28 21:44
@AnotherFoxGuy Pretty much yes. Let's close this ticket.

Originally I intended to implement a limited parsing mode for cache only, but never got to do it.

**Closed by only-a-ptr** 2017-03-28 21:44 UTC
Labels: enhancement, request
