### ISSUE TITLE
Localization doesn't work on ror next

### ISSUE THREAD

**Issue by Speciesx** [RigsOfRods/rigs-of-rods#82] opened 2015-02-18 16:52 UTC
The localization files from ror 0.4.0.7 doesn't work on ror next.

**Comment by Max98** [comment] 2015-02-18 18:57
I don't really understand this. What's the localization? Any pictures? Video?

**Comment by Speciesx** [comment] 2015-02-18 19:17
http://en.wikipedia.org/wiki/Internationalization_and_localization

**Comment by Max98** [comment] 2015-02-18 20:26
Oh, language selection? I see.

**Comment by Hiradur** [comment] 2015-10-24 08:56
Closing as duplicate of #391

**Closed by Hiradur** 2015-10-24 08:56 UTC
Labels: bug, duplicate, low-priority
