### ISSUE TITLE
Voulk buses don't work

### ISSUE THREAD

**Issue by TechGiga** [RigsOfRods/rigs-of-rods#371] opened 2015-08-10 02:19 UTC
Although many other bugs have been fixed (like the monster bus spawning without wheels), which is awesome :+1: , the Voulk buses don't work. The Thomas 3800 is the one I tried, have not tried the others. When you first spawn it, the camera is super far away. Then once you can see the bus, it does not accelerate, turn, or do anything.

**Comment by Hiradur** [comment] 2015-08-10 08:09
link to vehicles, please

**Comment by DirtGamer301** [comment] 2015-08-10 08:46
@Hiradur 
http://www.rigsofrods.com/threads/110205-Voulk-s-school-bus-pack

**Comment by gigapouch** [comment] 2015-08-10 15:20
You're correct dirtgamer.

**Comment by DarthCainRor** [comment] 2015-08-11 03:26
Most of my T800's seem to be doing the same. I've even fixed all the simple errors it was giving, besides the outdated meshes, but when you spawn it outside of the garage your camera goes way far away, with the speedo at max. When you spawn it in the garage it appears to be in a constant state of respawn, with the speedo at max. http://www.rigsofrods.com/threads/88541-Kenworth-T800SH-Trucks-with-Meyer-Road-Pro-plow?p=982235&viewfull=1#post982235

Log after fixing errors: http://pastebin.com/Wie5Bg3K

**Comment by DarthCainRor** [comment] 2015-08-12 09:51
Ok, with fidoj's help we've discovered that the error with spawning both my t800, and voulk's buses, lies in the "fusedrag" section, as without it, they all spawn perfectly fine.

**Comment by fidoj** [comment] 2015-08-12 09:54
i feel this error is also present in other error's, ie if you set setbeams to high the game crash's, instead of the vehicle exploding.

**Comment by fidoj** [comment] 2015-08-18 19:30
related
![screenshot_146](https://cloud.githubusercontent.com/assets/12094306/9340495/99809be6-4622-11e5-8075-919ed5389253.jpg)

**Comment by gigapouch** [comment] 2015-08-18 21:43
@fidoj Yes, that happens with some other vehicles that worked in 0.38 as well.

**Comment by only-a-ptr** [comment] 2015-09-25 11:31
@fidoj @TechGiga Links, please.

@DarthCainRor Autocalc is broken, it's reported.

**Comment by Hiradur** [comment] 2015-10-24 17:41
Closing as duplicate of #134

**Closed by Hiradur** 2015-10-24 17:41 UTC
Labels: bug
